/** Auto-generated by scripts/generate-fortnite-content.mjs */
export type ForumSection = {
  heading: string
  body: string[]
}

export type ForumThread = {
  slug: string
  title: string
  excerpt: string
  metaTitle: string
  metaDescription: string
  searchTerms: string
  date: string
  readMinutes: number
  tag: string
  community: string
  author: string
  score: number
  sections: ForumSection[]
  howTo?: boolean
}

export const FORUM_THREADS: ForumThread[] = [
  {
    "slug": "fortnite-spoofer-discussion",
    "title": "Daily thread: fortnite spoofer, EAC patches, and loader status",
    "excerpt": "Open discussion for fortnite spoofer utilities, HWID profiles, and Easy Anti-Cheat rumors — read pinned rules first.",
    "metaTitle": "Daily thread: fortnite spoofer, EAC patches, and loader status | Fortnite Spoofer Forums",
    "metaDescription": "Open discussion for fortnite spoofer utilities, HWID profiles, and Easy Anti-Cheat rumors — read pinned rules first.",
    "searchTerms": "fortnite spoofer,  spoofer fortnite",
    "date": "2026-03-05",
    "readMinutes": 6,
    "tag": "General",
    "community": "fnspoofer",
    "author": "EACWatcher",
    "score": 381,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Open discussion for fortnite spoofer utilities, HWID profiles, and Easy Anti-Cheat rumors — read pinned rules first.",
          "Community: r/fnspoofer · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "hwid-spoofer-fortnite",
    "title": "hwid spoofer fortnite — setup, cleaner, and Fortnite tournaments",
    "excerpt": "Fortnite-focused HWID spoofer thread: cleaner order, tournament mode, and when to re-apply profiles.",
    "metaTitle": "hwid spoofer fortnite — setup, cleaner, and Fortnite tournaments | Fortnite Spoofer Forums",
    "metaDescription": "Fortnite-focused HWID spoofer thread: cleaner order, tournament mode, and when to re-apply profiles.",
    "searchTerms": "hwid spoofer fortnite,  fortnite hwid spoofer",
    "date": "2026-03-06",
    "readMinutes": 7,
    "tag": "Spoofer",
    "community": "HWIDFortnite",
    "author": "DiskSerial",
    "score": 665,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Fortnite-focused HWID spoofer thread: cleaner order, tournament mode, and when to re-apply profiles.",
          "Community: r/HWIDFortnite · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "free-fortnite-spoofer-myths",
    "title": "free fortnite spoofer links — malware and incomplete rewrites",
    "excerpt": "Why free fortnite spoofer downloads fail EAC checks and often ship trojans — use official checkout only.",
    "metaTitle": "free fortnite spoofer links — malware and incomplete rewrites | Fortnite Spoofer Forums",
    "metaDescription": "Why free fortnite spoofer downloads fail EAC checks and often ship trojans — use official checkout only.",
    "searchTerms": "free fortnite spoofer,  fortnite spoofer free",
    "date": "2026-03-07",
    "readMinutes": 8,
    "tag": "Safety",
    "community": "ScamWatch",
    "author": "DefenderFan",
    "score": 895,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Why free fortnite spoofer downloads fail EAC checks and often ship trojans — use official checkout only.",
          "Community: r/ScamWatch · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "best-fortnite-spoofer-picks",
    "title": "best fortnite spoofer / best spoofer for fortnite — 2026 comparison",
    "excerpt": "Compare paid HWID utilities for Fortnite: backup tools, EAC title list, and support response times.",
    "metaTitle": "best fortnite spoofer / best spoofer for fortnite — 2026 comparison | Fortnite Spoofer Forums",
    "metaDescription": "Compare paid HWID utilities for Fortnite: backup tools, EAC title list, and support response times.",
    "searchTerms": "best fortnite spoofer,  best spoofer fortnite",
    "date": "2026-03-08",
    "readMinutes": 9,
    "tag": "Reviews",
    "community": "SpooferDeals",
    "author": "PermSpoof",
    "score": 630,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Compare paid HWID utilities for Fortnite: backup tools, EAC title list, and support response times.",
          "Community: r/SpooferDeals · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "fortnite-cheats-discussion",
    "title": "fortnite cheats — ESP defaults, aim smoothing, and reports",
    "excerpt": "Community thread for fortnite cheats features — keep cheat keywords here, not on spoofer product pages.",
    "metaTitle": "fortnite cheats — ESP defaults, aim smoothing, and reports | Fortnite Spoofer Forums",
    "metaDescription": "Community thread for fortnite cheats features — keep cheat keywords here, not on spoofer product pages.",
    "searchTerms": "fortnite cheats,  cheats for fortnite",
    "date": "2026-03-09",
    "readMinutes": 6,
    "tag": "Cheats",
    "community": "FortniteCheats",
    "author": "BoxESP",
    "score": 199,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Community thread for fortnite cheats features — keep cheat keywords here, not on spoofer product pages.",
          "Community: r/FortniteCheats · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "best-fortnite-cheats-thread",
    "title": "best fortnite cheats — legit presets vs rage configs",
    "excerpt": "Share legit ESP and aimbot presets for fortnite cheats buyers; moderators lock crack links.",
    "metaTitle": "best fortnite cheats — legit presets vs rage configs | Fortnite Spoofer Forums",
    "metaDescription": "Share legit ESP and aimbot presets for fortnite cheats buyers; moderators lock crack links.",
    "searchTerms": "best fortnite cheats,  cheats fortnite",
    "date": "2026-03-10",
    "readMinutes": 7,
    "tag": "Cheats",
    "community": "FortniteCheats",
    "author": "SmoothAim",
    "score": 466,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Share legit ESP and aimbot presets for fortnite cheats buyers; moderators lock crack links.",
          "Community: r/FortniteCheats · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "free-fortnite-cheats-reddit",
    "title": "free fortnite cheats reddit — navigational megathread",
    "excerpt": "Central thread for free fortnite cheats reddit searches — points to official store and status page only.",
    "metaTitle": "free fortnite cheats reddit — navigational megathread | Fortnite Spoofer Forums",
    "metaDescription": "Central thread for free fortnite cheats reddit searches — points to official store and status page only.",
    "searchTerms": "free fortnite cheats reddit,  free fortnite cheats",
    "date": "2026-03-11",
    "readMinutes": 8,
    "tag": "Cheats",
    "community": "FortniteCheats",
    "author": "ModTeam",
    "score": 638,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Central thread for free fortnite cheats reddit searches — points to official store and status page only.",
          "Community: r/FortniteCheats · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "ugc-account-recovery-help",
    "title": "UGC account recovery — Epic appeals and evidence logs",
    "excerpt": "Workflow tips for UGC tool buyers recovering Epic accounts alongside HWID utilities.",
    "metaTitle": "UGC account recovery — Epic appeals and evidence logs | Fortnite Spoofer Forums",
    "metaDescription": "Workflow tips for UGC tool buyers recovering Epic accounts alongside HWID utilities.",
    "searchTerms": "UGC account recovery,  fortnite spoofer",
    "date": "2026-03-12",
    "readMinutes": 9,
    "tag": "UGC",
    "community": "UGCRecovery",
    "author": "AppealBot",
    "score": 805,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Workflow tips for UGC tool buyers recovering Epic accounts alongside HWID utilities.",
          "Community: r/UGCRecovery · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "complete-setup",
    "title": "Fortnite Spoofer complete setup — backup, apply, verify HWID",
    "excerpt": "Step-by-step fortnite spoofer setup on fortnitespoofer.com: Defender exclusions, profile apply, EAC launch order.",
    "metaTitle": "Fortnite Spoofer complete setup — backup, apply, verify HWID | Fortnite Spoofer Forums",
    "metaDescription": "Step-by-step fortnite spoofer setup on fortnitespoofer.com: Defender exclusions, profile apply, EAC launch order.",
    "searchTerms": "fortnite spoofer,  hwid spoofer fortnite",
    "date": "2026-03-13",
    "readMinutes": 6,
    "tag": "Setup",
    "community": "FNSetup",
    "author": "support_fan",
    "score": 657,
    "sections": [
      {
        "heading": "1) Check status",
        "body": [
          "Step-by-step fortnite spoofer setup on fortnitespoofer.com: Defender exclusions, profile apply, EAC launch order.",
          "Community: r/FNSetup · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "2) Configure modules",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "features-list",
    "title": "Fortnite Spoofer feature list — hardware coverage & EAC games",
    "excerpt": "Official HWID utility checklist: disk, MAC, motherboard traces, cleaner, and supported EAC titles.",
    "metaTitle": "Fortnite Spoofer feature list — hardware coverage & EAC games | Fortnite Spoofer Forums",
    "metaDescription": "Official HWID utility checklist: disk, MAC, motherboard traces, cleaner, and supported EAC titles.",
    "searchTerms": "fortnite spoofer,  hwid spoofer fortnite",
    "date": "2026-03-14",
    "readMinutes": 7,
    "tag": "Features",
    "community": "fnspoofer",
    "author": "FortniteSpooferMod",
    "score": 838,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Official HWID utility checklist: disk, MAC, motherboard traces, cleaner, and supported EAC titles.",
          "Community: r/fnspoofer · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "fortnite-cheats-features",
    "title": "Fortnite cheats feature list — visuals, aimbot, item ESP",
    "excerpt": "Full fortnite cheats module list: box ESP, skeleton, radar, weapon configs, and item filters.",
    "metaTitle": "Fortnite cheats feature list — visuals, aimbot, item ESP | Fortnite Spoofer Forums",
    "metaDescription": "Full fortnite cheats module list: box ESP, skeleton, radar, weapon configs, and item filters.",
    "searchTerms": "fortnite cheats,  cheats for fortnite",
    "date": "2026-03-15",
    "readMinutes": 8,
    "tag": "Features",
    "community": "FortniteCheats",
    "author": "FortniteSpooferMod",
    "score": 956,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Full fortnite cheats module list: box ESP, skeleton, radar, weapon configs, and item filters.",
          "Community: r/FortniteCheats · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "eac-fortnite-status",
    "title": "Fortnite EAC status — Active vs Updating after patches",
    "excerpt": "When Epic ships a Fortnite update, loader status may flip Updating — wait for Active before load.",
    "metaTitle": "Fortnite EAC status — Active vs Updating after patches | Fortnite Spoofer Forums",
    "metaDescription": "When Epic ships a Fortnite update, loader status may flip Updating — wait for Active before load.",
    "searchTerms": "fortnite spoofer,  fortnite cheats",
    "date": "2026-03-16",
    "readMinutes": 9,
    "tag": "Patches",
    "community": "PatchWatch",
    "author": "patch_day_survivor",
    "score": 330,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "When Epic ships a Fortnite update, loader status may flip Updating — wait for Active before load.",
          "Community: r/PatchWatch · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "loader-errors",
    "title": "Loader closes / menu missing — fortnite spoofer fix list",
    "excerpt": "Menu not opening, quarantine, wrong build — confirm Active status before re-applying HWID profiles.",
    "metaTitle": "Loader closes / menu missing — fortnite spoofer fix list | Fortnite Spoofer Forums",
    "metaDescription": "Menu not opening, quarantine, wrong build — confirm Active status before re-applying HWID profiles.",
    "searchTerms": "fortnite spoofer,  hwid spoofer fortnite",
    "date": "2026-03-17",
    "readMinutes": 6,
    "tag": "Support",
    "community": "LoaderHelp",
    "author": "defender_hater",
    "score": 157,
    "sections": [
      {
        "heading": "1) Check status",
        "body": [
          "Menu not opening, quarantine, wrong build — confirm Active status before re-applying HWID profiles.",
          "Community: r/LoaderHelp · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "2) Configure modules",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "lifetime-vs-monthly",
    "title": "Lifetime vs monthly ($150 vs $35) for all store products",
    "excerpt": "Compare monthly P30D and lifetime P99Y for spoofer, cheats, and UGC on fortnitespoofer.com.",
    "metaTitle": "Lifetime vs monthly ($150 vs $35) for all store products | Fortnite Spoofer Forums",
    "metaDescription": "Compare monthly P30D and lifetime P99Y for spoofer, cheats, and UGC on fortnitespoofer.com.",
    "searchTerms": "fortnite spoofer,  fortnite cheats",
    "date": "2026-03-18",
    "readMinutes": 7,
    "tag": "Plans",
    "community": "FNDeals",
    "author": "longterm_core",
    "score": 201,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Compare monthly P30D and lifetime P99Y for spoofer, cheats, and UGC on fortnitespoofer.com.",
          "Community: r/FNDeals · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  },
  {
    "slug": "hwid-spoofer-reddit",
    "title": "hwid spoofer fortnite reddit — official links only",
    "excerpt": "Navigational thread: use fortnitespoofer.com store and support — no third-party key resellers.",
    "metaTitle": "hwid spoofer fortnite reddit — official links only | Fortnite Spoofer Forums",
    "metaDescription": "Navigational thread: use fortnitespoofer.com store and support — no third-party key resellers.",
    "searchTerms": "hwid spoofer fortnite reddit,  hwid spoofer free fortnite",
    "date": "2026-03-19",
    "readMinutes": 8,
    "tag": "Nav",
    "community": "fnspoofer",
    "author": "ModTeam",
    "score": 800,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Navigational thread: use fortnitespoofer.com store and support — no third-party key resellers.",
          "Community: r/fnspoofer · Game: Fortnite · Anti-cheat: Easy Anti-Cheat (EAC). Official site: fortnitespoofer.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "HWID utilities, fortnite spoofer setup, fortnite cheats modules, and UGC recovery workflows are documented on their respective feature threads.",
          "Moderators may lock threads that share crack links, stolen keys, or unrelated game cheats that cannibalize SEO."
        ]
      }
    ]
  }
]

export function getForumThread(slug: string) {
  return FORUM_THREADS.find((f) => f.slug === slug)
}

export function getRelatedForumThreads(slug: string, limit = 6): ForumThread[] {
  const current = getForumThread(slug)
  if (!current) return []
  return FORUM_THREADS.filter((f) => f.slug !== slug)
    .sort((a, b) => {
      const tagRank = (p: ForumThread) => (p.tag === current.tag ? 0 : 1)
      return tagRank(a) - tagRank(b) || a.title.localeCompare(b.title)
    })
    .slice(0, limit)
}

export { forumPath } from './blog-paths'
