/** Auto-generated by scripts/generate-fortnite-content.mjs */
export type ForumReplyRole = 'editor' | 'moderator' | 'member'

export type ForumReply = {
  author: string
  date: string
  body: string
  role?: ForumReplyRole
  replyToAuthor?: string
}

export const FORUM_REPLIES: Record<string, ForumReply[]> = {
  "fortnite-spoofer-discussion": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-13",
      "body": "Editor: pinned General reference for r/fnspoofer. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-17",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "LoaderGhost",
      "role": "member",
      "date": "2026-03-21",
      "body": "Followed the setup thread — profile backup and audit log came up first try after Defender exclusion."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-03-22",
      "body": "Ranked thread is depressing but accurate. Reports stack if you play blatant."
    },
    {
      "author": "FortniteSpooferMod",
      "role": "member",
      "date": "2026-03-23",
      "body": "Status page matched menu after Epic patch; fewer surprise HWID locks."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@LoaderGhost — walk the General checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "LoaderGhost"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@IT_guy_gaming — walk the General checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "IT_guy_gaming"
    }
  ],
  "hwid-spoofer-fortnite": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned Spoofer reference for r/HWIDFortnite. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-13",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "EACWatcher",
      "role": "member",
      "date": "2026-03-25",
      "body": "Menu never opened until I restored Defender quarantine. Skipped that step first time."
    },
    {
      "author": "DiskSerial",
      "role": "member",
      "date": "2026-03-26",
      "body": "Session isolation plus low-opacity ESP feels readable in Creative."
    },
    {
      "author": "BoxESP",
      "role": "member",
      "date": "2026-03-27",
      "body": "Compatibility checker caught Secure Boot before I wasted a ban appeal — not magic but consistent."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@EACWatcher — walk the Spoofer checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "EACWatcher"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@BoxESP — walk the Spoofer checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "BoxESP"
    }
  ],
  "free-fortnite-spoofer-myths": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned Safety reference for r/ScamWatch. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "EACWatcher",
      "role": "member",
      "date": "2026-03-19",
      "body": "Ranked thread is depressing but accurate. Reports stack if you play blatant."
    },
    {
      "author": "DiskSerial",
      "role": "member",
      "date": "2026-03-20",
      "body": "Status page matched menu after Epic patch; fewer surprise HWID locks."
    },
    {
      "author": "BoxESP",
      "role": "member",
      "date": "2026-03-21",
      "body": "Lifetime plan paid off after the third month — still on Active after last Fortnite patch."
    },
    {
      "author": "SmoothAim",
      "role": "member",
      "date": "2026-03-22",
      "body": "Menu never opened until I restored Defender quarantine. Skipped that step first time."
    },
    {
      "author": "PermSpoof",
      "role": "member",
      "date": "2026-03-23",
      "body": "Session isolation plus low-opacity ESP feels readable in Creative."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@EACWatcher — walk the Safety checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "EACWatcher"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@SmoothAim — walk the Safety checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "SmoothAim"
    }
  ],
  "best-fortnite-spoofer-picks": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-10",
      "body": "Editor: pinned Reviews reference for r/SpooferDeals. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "DefenderFan",
      "role": "member",
      "date": "2026-03-24",
      "body": "Session isolation plus low-opacity ESP feels readable in Creative."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-03-25",
      "body": "Thought HWID spoofer replaces a ban — it does not. Read the safety blog."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-03-26",
      "body": "Followed the setup thread — profile backup and audit log came up first try after Defender exclusion."
    },
    {
      "author": "longterm_core",
      "role": "member",
      "date": "2026-03-27",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@DefenderFan — walk the Reviews checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "DefenderFan"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@longterm_core — walk the Reviews checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "longterm_core"
    }
  ],
  "fortnite-cheats-discussion": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-13",
      "body": "Editor: pinned Cheats reference for r/FortniteCheats. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-03-27",
      "body": "Compatibility checker caught Secure Boot before I wasted a ban appeal — not magic but consistent."
    },
    {
      "author": "EACWatcher",
      "role": "member",
      "date": "2026-03-10",
      "body": "Loaded during Updating after a patch — instant close. Status page was right."
    },
    {
      "author": "DiskSerial",
      "role": "member",
      "date": "2026-03-11",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "BoxESP",
      "role": "member",
      "date": "2026-03-12",
      "body": "Status page matched menu after Epic patch; fewer surprise HWID locks."
    },
    {
      "author": "SmoothAim",
      "role": "member",
      "date": "2026-03-13",
      "body": "Expected free spoofer links here — mod locked it and pointed to safety FAQ. Fair."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@irritated_panda — walk the Cheats checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "irritated_panda"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@SmoothAim — walk the Cheats checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "SmoothAim"
    }
  ],
  "best-fortnite-cheats-thread": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-12",
      "body": "Editor: pinned Cheats reference for r/FortniteCheats. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-14",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "DiskSerial",
      "role": "member",
      "date": "2026-03-26",
      "body": "Followed the setup thread — profile backup and audit log came up first try after Defender exclusion."
    },
    {
      "author": "BoxESP",
      "role": "member",
      "date": "2026-03-27",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "SmoothAim",
      "role": "member",
      "date": "2026-03-10",
      "body": "Monthly vs lifetime pricing confused me until Support replied same day."
    },
    {
      "author": "PermSpoof",
      "role": "member",
      "date": "2026-03-11",
      "body": "Lifetime plan paid off after the third month — still on Active after last Fortnite patch."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@DiskSerial — walk the Cheats checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "DiskSerial"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@SmoothAim — walk the Cheats checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "SmoothAim"
    }
  ],
  "free-fortnite-cheats-reddit": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-08",
      "body": "Editor: pinned Cheats reference for r/FortniteCheats. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "SmoothAim",
      "role": "member",
      "date": "2026-03-10",
      "body": "Loaded during Updating after a patch — instant close. Status page was right."
    },
    {
      "author": "PermSpoof",
      "role": "member",
      "date": "2026-03-11",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "DefenderFan",
      "role": "member",
      "date": "2026-03-12",
      "body": "Status page matched menu after Epic patch; fewer surprise HWID locks."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-03-13",
      "body": "Expected free spoofer links here — mod locked it and pointed to safety FAQ. Fair."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@SmoothAim — walk the Cheats checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "SmoothAim"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@PermSpoof — walk the Cheats checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "PermSpoof"
    }
  ],
  "ugc-account-recovery-help": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned UGC reference for r/UGCRecovery. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-17",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "EACWatcher",
      "role": "member",
      "date": "2026-03-25",
      "body": "Monthly vs lifetime pricing confused me until Support replied same day."
    },
    {
      "author": "DiskSerial",
      "role": "member",
      "date": "2026-03-26",
      "body": "Lifetime plan paid off after the third month — still on Active after last Fortnite patch."
    },
    {
      "author": "BoxESP",
      "role": "member",
      "date": "2026-03-27",
      "body": "EAC thread scared me straight — staying on smurf for spoofer testing only."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@EACWatcher — walk the UGC checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "EACWatcher"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@BoxESP — walk the UGC checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "BoxESP"
    }
  ],
  "complete-setup": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned Setup reference for r/FNSetup. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-13",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-03-13",
      "body": "Thought HWID spoofer replaces a ban — it does not. Read the safety blog."
    },
    {
      "author": "FortniteSpooferMod",
      "role": "member",
      "date": "2026-03-14",
      "body": "Followed the setup thread — profile backup and audit log came up first try after Defender exclusion."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-03-15",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@IT_guy_gaming — walk the Setup checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "IT_guy_gaming"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@irritated_panda — walk the Setup checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "irritated_panda"
    }
  ],
  "features-list": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-08",
      "body": "Editor: pinned Features reference for r/fnspoofer. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "SmoothAim",
      "role": "member",
      "date": "2026-03-16",
      "body": "Thought HWID spoofer replaces a ban — it does not. Read the safety blog."
    },
    {
      "author": "PermSpoof",
      "role": "member",
      "date": "2026-03-17",
      "body": "Followed the setup thread — profile backup and audit log came up first try after Defender exclusion."
    },
    {
      "author": "DefenderFan",
      "role": "member",
      "date": "2026-03-18",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-03-19",
      "body": "Monthly vs lifetime pricing confused me until Support replied same day."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@SmoothAim — walk the Features checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "SmoothAim"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@patch_day_survivor — walk the Features checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "patch_day_survivor"
    }
  ],
  "fortnite-cheats-features": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-08",
      "body": "Editor: pinned Features reference for r/FortniteCheats. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-16",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-03-22",
      "body": "Ranked thread is depressing but accurate. Reports stack if you play blatant."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-03-23",
      "body": "Status page matched menu after Epic patch; fewer surprise HWID locks."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@patch_day_survivor — walk the Features checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "patch_day_survivor"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@defender_hater — walk the Features checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "defender_hater"
    }
  ],
  "eac-fortnite-status": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-10",
      "body": "Editor: pinned Patches reference for r/PatchWatch. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-14",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "DefenderFan",
      "role": "member",
      "date": "2026-03-24",
      "body": "Status page matched menu after Epic patch; fewer surprise HWID locks."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-03-25",
      "body": "Expected free spoofer links here — mod locked it and pointed to safety FAQ. Fair."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-03-26",
      "body": "EAC thread scared me straight — staying on smurf for spoofer testing only."
    },
    {
      "author": "longterm_core",
      "role": "member",
      "date": "2026-03-27",
      "body": "Session isolation plus low-opacity ESP feels readable in Creative."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@DefenderFan — walk the Patches checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "DefenderFan"
    }
  ],
  "loader-errors": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned Support reference for r/LoaderHelp. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-17",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-03-13",
      "body": "Menu never opened until I restored Defender quarantine. Skipped that step first time."
    },
    {
      "author": "FortniteSpooferMod",
      "role": "member",
      "date": "2026-03-14",
      "body": "Session isolation plus low-opacity ESP feels readable in Creative."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-03-15",
      "body": "Compatibility checker caught Secure Boot before I wasted a ban appeal — not magic but consistent."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@IT_guy_gaming — walk the Support checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "IT_guy_gaming"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@irritated_panda — walk the Support checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "irritated_panda"
    }
  ],
  "lifetime-vs-monthly": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned Plans reference for r/FNDeals. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-13",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-03-13",
      "body": "Menu never opened until I restored Defender quarantine. Skipped that step first time."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-03-14",
      "body": "Session isolation plus low-opacity ESP feels readable in Creative."
    },
    {
      "author": "longterm_core",
      "role": "member",
      "date": "2026-03-15",
      "body": "Compatibility checker caught Secure Boot before I wasted a ban appeal — not magic but consistent."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@patch_day_survivor — walk the Plans checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "patch_day_survivor"
    },
    {
      "author": "Fortnite Spoofer Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@longterm_core — walk the Plans checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "longterm_core"
    }
  ],
  "hwid-spoofer-reddit": [
    {
      "author": "FortniteSpoofer Editor",
      "role": "editor",
      "date": "2026-03-08",
      "body": "Editor: pinned Nav reference for r/fnspoofer. Matches fortnitespoofer.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-12",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via fortnitespoofer.com."
    },
    {
      "author": "EACWatcher",
      "role": "member",
      "date": "2026-03-22",
      "body": "Monthly vs lifetime pricing confused me until Support replied same day."
    },
    {
      "author": "DiskSerial",
      "role": "member",
      "date": "2026-03-23",
      "body": "Lifetime plan paid off after the third month — still on Active after last Fortnite patch."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@EACWatcher — walk the Nav checklist in the OP, confirm Active on fortnitespoofer.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "EACWatcher"
    }
  ]
}

export function getForumReplies(slug: string): ForumReply[] {
  return FORUM_REPLIES[slug] ?? []
}
